### PR TITLE
The default value of flex-basis is 0%

### PR DESCRIPTION
**Pull request by silvenon**
Sorry for giving you the wrong info in #21 :sweat_smile:  The **initial** value is `auto`, I got them mixed up. Let me make it up to you by submitting a PR.

These are tests for now, code will come soon.

### CODE REVIEW

**Comment by silvenon** [comment]
Ready.

But contains changes from #22, so that one should be pulled first. (Should've made it a one PR instead of two, my bad.)

**Comment by luisrudge** [comment]
ok, I merged #24. can you fix the conflicts? Thanks so much for your help!

**Comment by silvenon** [comment]
Fixed. No problem, thanks for making the plugin :+1: (You could submit a PR to the flexbugs repo linking to this plugin.)

**Comment by luisrudge** [comment]
published https://www.npmjs.com/package/postcss-flexbugs-fixes

**Comment by silvenon** [comment]
Awesome!

**Pull request merged**
